name: Dock
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
jobs:
  images:
    name: Build and Push images
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Setup dock-cli
      run: make clean init
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build Docker Images
      run: make build-images
    - name: Login to DockerHub
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker Images
      if: github.event_name == 'push'
      run: make push-images
    - name: Clean Docker Images
      if: always()
      run: make clean-images
    - name: Clean dock-cli
      if: always()
      run: make clean
  charts:
    name: Package and Push charts
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Setup dock-cli
      run: make clean init
    - name: Setup Helm
      uses: azure/setup-helm@v4.1.0
    - name: Package Helm Charts
      run: make package-charts
    - name: Login to DockerHub
      if: github.event_name == 'push'
      run: echo ${{ secrets.DOCKER_PASSWORD }} | helm registry login registry-1.docker.io --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Push Helm Charts
      if: github.event_name == 'push'
      run: make push-charts
    - name: Logout from DockerHub
      if: always() && github.event_name == 'push'
      run: helm registry logout registry-1.docker.io
    - name: Clean Helm Charts
      if: always()
      run: make clean-charts
    - name: Clean dock-cli
      if: always()
      run: make clean
